/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fractal;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Lenovo
 */
public class trianSierpinski extends javax.swing.JFrame {

    /**
     * Creates new form trianSierpinski
     */
    public trianSierpinski() {
        initComponents();
    }
    
    private int profundidad;//Declaracion de la variable para la profundidad o cantidad de triangulos internos
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        panelFractal = new javax.swing.JPanel();
        profund = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dibujar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Triangulo de Sierpinski");
        setPreferredSize(new java.awt.Dimension(700, 800));
        setSize(new java.awt.Dimension(700, 700));

        panelFractal.setBackground(new java.awt.Color(255, 255, 255));
        panelFractal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelFractal.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelFractalLayout = new javax.swing.GroupLayout(panelFractal);
        panelFractal.setLayout(panelFractalLayout);
        panelFractalLayout.setHorizontalGroup(
            panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        panelFractalLayout.setVerticalGroup(
            panelFractalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        profund.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        profund.setText("5");
        profund.setMaximumSize(new java.awt.Dimension(40, 22));
        profund.setName("prof"); // NOI18N
        profund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profundActionPerformed(evt);
            }
        });

        jLabel1.setText("Profundidad");

        dibujar.setText("Dibujar");
        dibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Triangulo de Sierpinski");

        jLabel3.setText("By: Gildardo Tello Alvarez");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(610, 610, 610)))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelFractal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(profund, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dibujar)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dibujar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFractal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujarActionPerformed

    profundidad = Integer.parseInt(profund.getText());// Profundidad ingresada por el usuario en el textField
    
    panelFractal.getGraphics().clearRect(0, 0, panelFractal.getWidth(), panelFractal.getHeight());// Limpia el panel antes de dibujar
    
    // Inicializamos las variables que contienen las coordenadas de los vértices del primer triángulo
    int x1 = 50;
    int y1 = 550;
    int x2 = 300;
    int y2 = 50;
    int x3 = 550;
    int y3 = 550;

    // Llamamos a la función para dibujar el Triángulo de Sierpinski
    dibujarTriangulo(profundidad, x1, y1, x2, y2, x3, y3);
    }//GEN-LAST:event_dibujarActionPerformed

    private void profundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profundActionPerformed

    // Función recursiva para dibujar el Triángulo de Sierpinski
private void dibujarTriangulo(int prof, int x1, int y1, int x2, int y2, int x3, int y3) {
    if (prof == 0) {
        // caso en el que se dibuja un triángulo
        
        panelFractal.getGraphics().drawPolygon(new int[]{x1, x2, x3}, new int[]{y1, y2, y3}, 3);
    } else {
        // Calculos para los puntos medios de los lados del triángulo
        int mx1 = (x1 + x2) / 2;
        int my1 = (y1 + y2) / 2;
        int mx2 = (x2 + x3) / 2;
        int my2 = (y2 + y3) / 2;
        int mx3 = (x1 + x3) / 2;
        int my3 = (y1 + y3) / 2;

        // Se vuelve a llamar a la funcion para que dibuje los subtriangulos
        dibujarTriangulo(prof - 1, x1, y1, mx1, my1, mx3, my3);
        dibujarTriangulo(prof - 1, mx1, my1, x2, y2, mx2, my2);
        dibujarTriangulo(prof - 1, mx3, my3, mx2, my2, x3, y3);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trianSierpinski.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trianSierpinski.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trianSierpinski.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trianSierpinski.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trianSierpinski().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton dibujar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelFractal;
    private javax.swing.JTextField profund;
    // End of variables declaration//GEN-END:variables
}
